/**
 * default_1501644919208
 * API接入，支持Java、C#、Php、Python等开发语言接入，可下发全球231+国家与地区手机。快速实现互联网企业跨国业务的开展。
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package api;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import wxlink.ApiCallback;
import wxlink.ApiClient;
import wxlink.ApiException;
import wxlink.ApiResponse;
import wxlink.Configuration;
import wxlink.Pair;
import wxlink.ProgressRequestBody;
import wxlink.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

public class DefaultApi {
    private ApiClient apiClient;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for intSms */
    private com.squareup.okhttp.Call intSmsCall(String mobile, String appkey, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // verify the required parameter 'mobile' is set
        if (mobile == null) {
            throw new ApiException("Missing the required parameter 'mobile' when calling intSms(Async)");
        }
        
        // verify the required parameter 'appkey' is set
        if (appkey == null) {
            throw new ApiException("Missing the required parameter 'appkey' when calling intSms(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/chonry/int_sms".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (mobile != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "mobile", mobile));
        if (appkey != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "appkey", appkey));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "text/plain"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知
     * @param mobile 接收短信的手机号码，多个号码以半角逗号,隔开 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String intSms(String mobile, String appkey) throws ApiException {
        ApiResponse<String> resp = intSmsWithHttpInfo(mobile, appkey);
        return resp.getData();
    }

    /**
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知
     * @param mobile 接收短信的手机号码，多个号码以半角逗号,隔开 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> intSmsWithHttpInfo(String mobile, String appkey) throws ApiException {
        com.squareup.okhttp.Call call = intSmsCall(mobile, appkey, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知 (asynchronously)
     * 国际短信、国际短信验证码、国际短信接口、国际短信通知
     * @param mobile 接收短信的手机号码，多个号码以半角逗号,隔开 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call intSmsAsync(String mobile, String appkey, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = intSmsCall(mobile, appkey, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
