package com.woman.pojo;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

public class company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyId
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyName
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remarkName
     *
     * @mbggenerated
     */
    private String remarkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.enterpriseType
     *
     * @mbggenerated
     */
    private String enterprisetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.registeredCapital
     *
     * @mbggenerated
     */
    private Integer registeredcapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.businessScope
     *
     * @mbggenerated
     */
    private String businessscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyType
     *
     * @mbggenerated
     */
    private String companytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.linkPhone
     *
     * @mbggenerated
     */
    private String linkphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.openid
     *
     * @mbggenerated
     */
    private String jscode;
    private String openid;
    

    private  List<shareholder>  shareholder;
    

  private int showState;



	public int getShowState() {
	return showState;
}

public void setShowState(int showState) {
	this.showState = showState;
}

	public List<shareholder> getShareholder() {
		return shareholder;
	}

	public void setShareholder(List<shareholder> shareholder) {
		this.shareholder = shareholder;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyId
     *
     * @return the value of company.companyId
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyId
     *
     * @param companyid the value for company.companyId
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyName
     *
     * @return the value of company.companyName
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyName
     *
     * @param companyname the value for company.companyName
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remarkName
     *
     * @return the value of company.remarkName
     *
     * @mbggenerated
     */
    public String getRemarkname() {
        return remarkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remarkName
     *
     * @param remarkname the value for company.remarkName
     *
     * @mbggenerated
     */
    public void setRemarkname(String remarkname) {
        this.remarkname = remarkname == null ? null : remarkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.enterpriseType
     *
     * @return the value of company.enterpriseType
     *
     * @mbggenerated
     */
    public String getEnterprisetype() {
        return enterprisetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.enterpriseType
     *
     * @param enterprisetype the value for company.enterpriseType
     *
     * @mbggenerated
     */
    public void setEnterprisetype(String enterprisetype) {
        this.enterprisetype = enterprisetype == null ? null : enterprisetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.registeredCapital
     *
     * @return the value of company.registeredCapital
     *
     * @mbggenerated
     */
    public Integer getRegisteredcapital() {
        return registeredcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.registeredCapital
     *
     * @param registeredcapital the value for company.registeredCapital
     *
     * @mbggenerated
     */
    public void setRegisteredcapital(Integer registeredcapital) {
        this.registeredcapital = registeredcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.businessScope
     *
     * @return the value of company.businessScope
     *
     * @mbggenerated
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.businessScope
     *
     * @param businessscope the value for company.businessScope
     *
     * @mbggenerated
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyType
     *
     * @return the value of company.companyType
     *
     * @mbggenerated
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyType
     *
     * @param companytype the value for company.companyType
     *
     * @mbggenerated
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype == null ? null : companytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.linkman
     *
     * @return the value of company.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.linkman
     *
     * @param linkman the value for company.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.linkPhone
     *
     * @return the value of company.linkPhone
     *
     * @mbggenerated
     */
    public String getLinkphone() {
        return linkphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.linkPhone
     *
     * @param linkphone the value for company.linkPhone
     *
     * @mbggenerated
     */
    public void setLinkphone(String linkphone) {
        this.linkphone = linkphone == null ? null : linkphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.createTime
     *
     * @return the value of company.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.createTime
     *
     * @param createtime the value for company.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.openid
     *
     * @return the value of company.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.openid
     *
     * @param openid the value for company.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    
    
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        company other = (company) that;
        return (this.getCompanyid() == null ? other.getCompanyid() == null : this.getCompanyid().equals(other.getCompanyid()))
            && (this.getCompanyname() == null ? other.getCompanyname() == null : this.getCompanyname().equals(other.getCompanyname()))
            && (this.getRemarkname() == null ? other.getRemarkname() == null : this.getRemarkname().equals(other.getRemarkname()))
            && (this.getEnterprisetype() == null ? other.getEnterprisetype() == null : this.getEnterprisetype().equals(other.getEnterprisetype()))
            && (this.getRegisteredcapital() == null ? other.getRegisteredcapital() == null : this.getRegisteredcapital().equals(other.getRegisteredcapital()))
            && (this.getBusinessscope() == null ? other.getBusinessscope() == null : this.getBusinessscope().equals(other.getBusinessscope()))
            && (this.getCompanytype() == null ? other.getCompanytype() == null : this.getCompanytype().equals(other.getCompanytype()))
            && (this.getLinkman() == null ? other.getLinkman() == null : this.getLinkman().equals(other.getLinkman()))
            && (this.getLinkphone() == null ? other.getLinkphone() == null : this.getLinkphone().equals(other.getLinkphone()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid()));
    }

    public String getJscode() {
		return jscode;
	}

	public void setJscode(String jscode) {
		this.jscode = jscode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCompanyid() == null) ? 0 : getCompanyid().hashCode());
        result = prime * result + ((getCompanyname() == null) ? 0 : getCompanyname().hashCode());
        result = prime * result + ((getRemarkname() == null) ? 0 : getRemarkname().hashCode());
        result = prime * result + ((getEnterprisetype() == null) ? 0 : getEnterprisetype().hashCode());
        result = prime * result + ((getRegisteredcapital() == null) ? 0 : getRegisteredcapital().hashCode());
        result = prime * result + ((getBusinessscope() == null) ? 0 : getBusinessscope().hashCode());
        result = prime * result + ((getCompanytype() == null) ? 0 : getCompanytype().hashCode());
        result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
        result = prime * result + ((getLinkphone() == null) ? 0 : getLinkphone().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
        return result;
    }

	@Override
	public String toString() {
		return "company [companyid=" + companyid + ", companyname=" + companyname + ", remarkname=" + remarkname
				+ ", enterprisetype=" + enterprisetype + ", registeredcapital=" + registeredcapital + ", businessscope="
				+ businessscope + ", companytype=" + companytype + ", linkman=" + linkman + ", linkphone=" + linkphone
				+ ", createtime=" + createtime + ", jscode=" + jscode + ", openid=" + openid + ", shareholder="
				+ shareholder + "]";
	}


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */

}