package com.woman.pojo;

import java.io.Serializable;

public class company_shareholder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shareholder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shareholder.companyid
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shareholder.shareholder
     *
     * @mbggenerated
     */
    private Integer shareholder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shareholder.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shareholder.id
     *
     * @return the value of company_shareholder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shareholder.id
     *
     * @param id the value for company_shareholder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shareholder.companyid
     *
     * @return the value of company_shareholder.companyid
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shareholder.companyid
     *
     * @param companyid the value for company_shareholder.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shareholder.shareholder
     *
     * @return the value of company_shareholder.shareholder
     *
     * @mbggenerated
     */
    public Integer getShareholder() {
        return shareholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shareholder.shareholder
     *
     * @param shareholder the value for company_shareholder.shareholder
     *
     * @mbggenerated
     */
    public void setShareholder(Integer shareholder) {
        this.shareholder = shareholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shareholder.createTime
     *
     * @return the value of company_shareholder.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shareholder.createTime
     *
     * @param createtime the value for company_shareholder.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        company_shareholder other = (company_shareholder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyid() == null ? other.getCompanyid() == null : this.getCompanyid().equals(other.getCompanyid()))
            && (this.getShareholder() == null ? other.getShareholder() == null : this.getShareholder().equals(other.getShareholder()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyid() == null) ? 0 : getCompanyid().hashCode());
        result = prime * result + ((getShareholder() == null) ? 0 : getShareholder().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyid=").append(companyid);
        sb.append(", shareholder=").append(shareholder);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}