package com.woman.pojo;

import java.io.Serializable;

public class loans implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.loansId
     *
     * @mbggenerated
     */
    private Integer loansid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.IDCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.workAdress
     *
     * @mbggenerated
     */
    private String workadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.loansTime
     *
     * @mbggenerated
     */
    private Integer loanstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.urgencyDegree
     *
     * @mbggenerated
     */
    private Integer urgencydegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.loansUse
     *
     * @mbggenerated
     */
    private String loansuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.haveCar
     *
     * @mbggenerated
     */
    private Integer havecar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.haveHouse
     *
     * @mbggenerated
     */
    private Integer havehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.haveSafeguard
     *
     * @mbggenerated
     */
    private Integer havesafeguard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.haveWarranty
     *
     * @mbggenerated
     */
    private Integer havewarranty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.haveStatement
     *
     * @mbggenerated
     */
    private Integer havestatement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.familyKnow
     *
     * @mbggenerated
     */
    private Integer familyknow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loans.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loans
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.loansId
     *
     * @return the value of loans.loansId
     *
     * @mbggenerated
     */
    public Integer getLoansid() {
        return loansid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.loansId
     *
     * @param loansid the value for loans.loansId
     *
     * @mbggenerated
     */
    public void setLoansid(Integer loansid) {
        this.loansid = loansid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.name
     *
     * @return the value of loans.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.name
     *
     * @param name the value for loans.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.sex
     *
     * @return the value of loans.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.sex
     *
     * @param sex the value for loans.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.phone
     *
     * @return the value of loans.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.phone
     *
     * @param phone the value for loans.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.IDCard
     *
     * @return the value of loans.IDCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.IDCard
     *
     * @param idcard the value for loans.IDCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.workAdress
     *
     * @return the value of loans.workAdress
     *
     * @mbggenerated
     */
    public String getWorkadress() {
        return workadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.workAdress
     *
     * @param workadress the value for loans.workAdress
     *
     * @mbggenerated
     */
    public void setWorkadress(String workadress) {
        this.workadress = workadress == null ? null : workadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.email
     *
     * @return the value of loans.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.email
     *
     * @param email the value for loans.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.count
     *
     * @return the value of loans.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.count
     *
     * @param count the value for loans.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.loansTime
     *
     * @return the value of loans.loansTime
     *
     * @mbggenerated
     */
    public Integer getLoanstime() {
        return loanstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.loansTime
     *
     * @param loanstime the value for loans.loansTime
     *
     * @mbggenerated
     */
    public void setLoanstime(Integer loanstime) {
        this.loanstime = loanstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.urgencyDegree
     *
     * @return the value of loans.urgencyDegree
     *
     * @mbggenerated
     */
    public Integer getUrgencydegree() {
        return urgencydegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.urgencyDegree
     *
     * @param urgencydegree the value for loans.urgencyDegree
     *
     * @mbggenerated
     */
    public void setUrgencydegree(Integer urgencydegree) {
        this.urgencydegree = urgencydegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.loansUse
     *
     * @return the value of loans.loansUse
     *
     * @mbggenerated
     */
    public String getLoansuse() {
        return loansuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.loansUse
     *
     * @param loansuse the value for loans.loansUse
     *
     * @mbggenerated
     */
    public void setLoansuse(String loansuse) {
        this.loansuse = loansuse == null ? null : loansuse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.haveCar
     *
     * @return the value of loans.haveCar
     *
     * @mbggenerated
     */
    public Integer getHavecar() {
        return havecar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.haveCar
     *
     * @param havecar the value for loans.haveCar
     *
     * @mbggenerated
     */
    public void setHavecar(Integer havecar) {
        this.havecar = havecar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.haveHouse
     *
     * @return the value of loans.haveHouse
     *
     * @mbggenerated
     */
    public Integer getHavehouse() {
        return havehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.haveHouse
     *
     * @param havehouse the value for loans.haveHouse
     *
     * @mbggenerated
     */
    public void setHavehouse(Integer havehouse) {
        this.havehouse = havehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.haveSafeguard
     *
     * @return the value of loans.haveSafeguard
     *
     * @mbggenerated
     */
    public Integer getHavesafeguard() {
        return havesafeguard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.haveSafeguard
     *
     * @param havesafeguard the value for loans.haveSafeguard
     *
     * @mbggenerated
     */
    public void setHavesafeguard(Integer havesafeguard) {
        this.havesafeguard = havesafeguard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.haveWarranty
     *
     * @return the value of loans.haveWarranty
     *
     * @mbggenerated
     */
    public Integer getHavewarranty() {
        return havewarranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.haveWarranty
     *
     * @param havewarranty the value for loans.haveWarranty
     *
     * @mbggenerated
     */
    public void setHavewarranty(Integer havewarranty) {
        this.havewarranty = havewarranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.haveStatement
     *
     * @return the value of loans.haveStatement
     *
     * @mbggenerated
     */
    public Integer getHavestatement() {
        return havestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.haveStatement
     *
     * @param havestatement the value for loans.haveStatement
     *
     * @mbggenerated
     */
    public void setHavestatement(Integer havestatement) {
        this.havestatement = havestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.familyKnow
     *
     * @return the value of loans.familyKnow
     *
     * @mbggenerated
     */
    public Integer getFamilyknow() {
        return familyknow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.familyKnow
     *
     * @param familyknow the value for loans.familyKnow
     *
     * @mbggenerated
     */
    public void setFamilyknow(Integer familyknow) {
        this.familyknow = familyknow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loans.createTime
     *
     * @return the value of loans.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loans.createTime
     *
     * @param createtime the value for loans.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loans
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        loans other = (loans) that;
        return (this.getLoansid() == null ? other.getLoansid() == null : this.getLoansid().equals(other.getLoansid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
            && (this.getWorkadress() == null ? other.getWorkadress() == null : this.getWorkadress().equals(other.getWorkadress()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getLoanstime() == null ? other.getLoanstime() == null : this.getLoanstime().equals(other.getLoanstime()))
            && (this.getUrgencydegree() == null ? other.getUrgencydegree() == null : this.getUrgencydegree().equals(other.getUrgencydegree()))
            && (this.getLoansuse() == null ? other.getLoansuse() == null : this.getLoansuse().equals(other.getLoansuse()))
            && (this.getHavecar() == null ? other.getHavecar() == null : this.getHavecar().equals(other.getHavecar()))
            && (this.getHavehouse() == null ? other.getHavehouse() == null : this.getHavehouse().equals(other.getHavehouse()))
            && (this.getHavesafeguard() == null ? other.getHavesafeguard() == null : this.getHavesafeguard().equals(other.getHavesafeguard()))
            && (this.getHavewarranty() == null ? other.getHavewarranty() == null : this.getHavewarranty().equals(other.getHavewarranty()))
            && (this.getHavestatement() == null ? other.getHavestatement() == null : this.getHavestatement().equals(other.getHavestatement()))
            && (this.getFamilyknow() == null ? other.getFamilyknow() == null : this.getFamilyknow().equals(other.getFamilyknow()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loans
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoansid() == null) ? 0 : getLoansid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getWorkadress() == null) ? 0 : getWorkadress().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getLoanstime() == null) ? 0 : getLoanstime().hashCode());
        result = prime * result + ((getUrgencydegree() == null) ? 0 : getUrgencydegree().hashCode());
        result = prime * result + ((getLoansuse() == null) ? 0 : getLoansuse().hashCode());
        result = prime * result + ((getHavecar() == null) ? 0 : getHavecar().hashCode());
        result = prime * result + ((getHavehouse() == null) ? 0 : getHavehouse().hashCode());
        result = prime * result + ((getHavesafeguard() == null) ? 0 : getHavesafeguard().hashCode());
        result = prime * result + ((getHavewarranty() == null) ? 0 : getHavewarranty().hashCode());
        result = prime * result + ((getHavestatement() == null) ? 0 : getHavestatement().hashCode());
        result = prime * result + ((getFamilyknow() == null) ? 0 : getFamilyknow().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loans
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loansid=").append(loansid);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", phone=").append(phone);
        sb.append(", idcard=").append(idcard);
        sb.append(", workadress=").append(workadress);
        sb.append(", email=").append(email);
        sb.append(", count=").append(count);
        sb.append(", loanstime=").append(loanstime);
        sb.append(", urgencydegree=").append(urgencydegree);
        sb.append(", loansuse=").append(loansuse);
        sb.append(", havecar=").append(havecar);
        sb.append(", havehouse=").append(havehouse);
        sb.append(", havesafeguard=").append(havesafeguard);
        sb.append(", havewarranty=").append(havewarranty);
        sb.append(", havestatement=").append(havestatement);
        sb.append(", familyknow=").append(familyknow);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}