package com.woman.pojo;

import java.io.Serializable;

public class shareholder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.shareholderId
     *
     * @mbggenerated
     */
   //股东id	
    private Integer shareholderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.name
     *
     * @mbggenerated
     */
    
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.holdScale
     *
     * @mbggenerated
     */
    private Integer holdscale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.IDCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.IDimg_z
     *
     * @mbggenerated
     */
    private String idimgZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.IDimg_f
     *
     * @mbggenerated
     */
    private String idimgF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder.createTime
     *
     * @mbggenerated
     */
    private String createtime;
    private int companyid;
    public int getCompanyid() {
		return companyid;
	}

	public void setCompanyid(int companyid) {
		this.companyid = companyid;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.shareholderId
     *
     * @return the value of shareholder.shareholderId
     *
     * @mbggenerated
     */
    public Integer getShareholderid() {
        return shareholderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.shareholderId
     *
     * @param shareholderid the value for shareholder.shareholderId
     *
     * @mbggenerated
     */
    public void setShareholderid(Integer shareholderid) {
        this.shareholderid = shareholderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.name
     *
     * @return the value of shareholder.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.name
     *
     * @param name the value for shareholder.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.phone
     *
     * @return the value of shareholder.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.phone
     *
     * @param phone the value for shareholder.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.email
     *
     * @return the value of shareholder.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.email
     *
     * @param email the value for shareholder.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.holdScale
     *
     * @return the value of shareholder.holdScale
     *
     * @mbggenerated
     */
    public Integer getHoldscale() {
        return holdscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.holdScale
     *
     * @param holdscale the value for shareholder.holdScale
     *
     * @mbggenerated
     */
    public void setHoldscale(Integer holdscale) {
        this.holdscale = holdscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.IDCard
     *
     * @return the value of shareholder.IDCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.IDCard
     *
     * @param idcard the value for shareholder.IDCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.IDimg_z
     *
     * @return the value of shareholder.IDimg_z
     *
     * @mbggenerated
     */
    public String getIdimgZ() {
        return idimgZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.IDimg_z
     *
     * @param idimgZ the value for shareholder.IDimg_z
     *
     * @mbggenerated
     */
    public void setIdimgZ(String idimgZ) {
        this.idimgZ = idimgZ == null ? null : idimgZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.IDimg_f
     *
     * @return the value of shareholder.IDimg_f
     *
     * @mbggenerated
     */
    public String getIdimgF() {
        return idimgF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.IDimg_f
     *
     * @param idimgF the value for shareholder.IDimg_f
     *
     * @mbggenerated
     */
    public void setIdimgF(String idimgF) {
        this.idimgF = idimgF == null ? null : idimgF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder.createTime
     *
     * @return the value of shareholder.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder.createTime
     *
     * @param createtime the value for shareholder.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        shareholder other = (shareholder) that;
        return (this.getShareholderid() == null ? other.getShareholderid() == null : this.getShareholderid().equals(other.getShareholderid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getHoldscale() == null ? other.getHoldscale() == null : this.getHoldscale().equals(other.getHoldscale()))
            && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
            && (this.getIdimgZ() == null ? other.getIdimgZ() == null : this.getIdimgZ().equals(other.getIdimgZ()))
            && (this.getIdimgF() == null ? other.getIdimgF() == null : this.getIdimgF().equals(other.getIdimgF()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShareholderid() == null) ? 0 : getShareholderid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getHoldscale() == null) ? 0 : getHoldscale().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getIdimgZ() == null) ? 0 : getIdimgZ().hashCode());
        result = prime * result + ((getIdimgF() == null) ? 0 : getIdimgF().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

	@Override
	public String toString() {
		return "shareholder [shareholderid=" + shareholderid + ", name=" + name + ", phone=" + phone + ", email="
				+ email + ", holdscale=" + holdscale + ", idcard=" + idcard + ", idimgZ=" + idimgZ + ", idimgF="
				+ idimgF + ", createtime=" + createtime + ", companyid=" + companyid + "]";
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */

}