package com.woman.pojo;

import java.io.Serializable;

public class swiper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper.swiperID
     *
     * @mbggenerated
     */
    private Integer swiperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swiper
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper.swiperID
     *
     * @return the value of swiper.swiperID
     *
     * @mbggenerated
     */
    public Integer getSwiperid() {
        return swiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper.swiperID
     *
     * @param swiperid the value for swiper.swiperID
     *
     * @mbggenerated
     */
    public void setSwiperid(Integer swiperid) {
        this.swiperid = swiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper.url
     *
     * @return the value of swiper.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper.url
     *
     * @param url the value for swiper.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper.createTime
     *
     * @return the value of swiper.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper.createTime
     *
     * @param createtime the value for swiper.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        swiper other = (swiper) that;
        return (this.getSwiperid() == null ? other.getSwiperid() == null : this.getSwiperid().equals(other.getSwiperid()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSwiperid() == null) ? 0 : getSwiperid().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", swiperid=").append(swiperid);
        sb.append(", url=").append(url);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}