package com.woman.dao;

import com.woman.pojo.company_shareholder;

public interface company_shareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    int insert(company_shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    int insertSelective(company_shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    company_shareholder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(company_shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shareholder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(company_shareholder record);
}