package com.woman.dao;

import java.util.HashMap;
import java.util.List;

import com.woman.pojo.company;
   
public interface companyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * T0his method corresponds to the database table company
     *
     * @mbggenerated
     */
    int insert(company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    int insertSelective(company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    company selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(company record);
//    查询公司名称
    int selectCompanyName(String name);
//    查询的集合
    List<company> findByPage(HashMap<String,Object> map);
//    查询总条数
    int SelectCount();
//    更加id查询公司和股东
    company selectCompanyId(int companyId);
//   修改查看状态
    int updateState(int companyId);
    //查询未查看的计数
    int selectState();
}