package com.woman.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.woman.pojo.notice;
public interface noticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int insert(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int insertSelective(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    notice selectByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(notice record);
    
    /*查询总记录数*/
    public Integer SelectCount(@Param("state")int state);
    
    
    /*分页查询*/
    List<notice> findByPage(HashMap<String,Object> map);
    
    /*查询最新公告*/
    List<notice> findBytime();
    
    /*按状态查询  （草稿箱  待发布   已发布）*/
    
    List<notice> findByState(HashMap<String,Object> map);
}