package com.woman.dao;

import com.woman.pojo.shareholder;

public interface shareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shareholderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    int insert(shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    int insertSelective(shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    shareholder selectByPrimaryKey(Integer shareholderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(shareholder record);
}