package com.woman.dao;

import com.woman.pojo.swiper;

public interface swiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer swiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    int insert(swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    int insertSelective(swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    swiper selectByPrimaryKey(Integer swiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(swiper record);
}